// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" with { type: "json" };
import * as $0 from "./routes/_middleware.tsx";
import * as $1 from "./routes/blog/[slug].ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/read/[slug].tsx";

const manifest = {
  routes: {
    "./routes/_middleware.tsx": $0,
    "./routes/blog/[slug].ts": $1,
    "./routes/index.tsx": $2,
    "./routes/read/[slug].tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
